# Generated by Django 5.2.2 on 2025-06-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dailies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='測定日')),
                ('prefecture_id', models.SmallIntegerField(verbose_name='都道府県ID')),
                ('station_name', models.CharField(max_length=128, verbose_name='測定地点名')),
                ('temperature_highest', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='最高気温（摂氏）')),
                ('temperature_lowest', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='最低気温（摂氏）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'prefecture_id', 'station_name'], name='weather_dat_date_05ad41_idx'), models.Index(fields=['date', 'station_name'], name='weather_dat_date_5227b4_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'prefecture_id', 'station_name'), name='unique_date_prefecture_id_station_name')],
                'unique_together': {('date', 'prefecture_id', 'station_name')},
            },
        ),
    ]
