# Generated by Django 5.2.2 on 2025-06-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailies',
            name='temperature_highest',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='最高気温（摂氏）'),
        ),
        migrations.AlterField(
            model_name='dailies',
            name='temperature_lowest',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='最低気温（摂氏）'),
        ),
    ]
