# Generated by Django 5.2.2 on 2025-06-16 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data', '0002_alter_dailies_temperature_highest_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dailies',
            new_name='Daily',
        ),
        migrations.RenameIndex(
            model_name='daily',
            new_name='weather_dat_date_92f339_idx',
            old_name='weather_dat_date_05ad41_idx',
        ),
        migrations.RenameIndex(
            model_name='daily',
            new_name='weather_dat_date_7e0b4d_idx',
            old_name='weather_dat_date_5227b4_idx',
        ),
    ]
